### ISSUE TITLE
[FE][FEAT] 카테고리 세부 페이지 제작

### ISSUE THREAD

**Issue by alpaka206** [memoney-app/memoney-frontend-web#13]
## 💻 Feature 설명
> 카테고리 세부 페이지 제작
<br>

## 📝 To-do
**메인주제**
- [x] Top-nav 만들
- [x] 이모티콘 넣기
- [x] 선택한 거 텍스트로 보여주기
- [x] 돈 누르면 원하는돈만 보이도록 하기
- [x] sort 작동 시키기
<br>

## 📸 스크린샷

<br>

## 📚 참고문헌 / 기타
-
