### ISSUE TITLE
[FE][FEAT] 받은돈, 나간돈 표시 구분

### ISSUE THREAD

**Issue by alpaka206** [memoney-app/memoney-frontend-web#20]
## 💻 Feature 설명
> 받은돈, 나간돈 표시 구분
<br>

## 📝 To-do
**메인주제**
- [x] 받은 돈만 표시
- [x] 받은 돈 총액 표시
- [x] 받은 돈 애니메이션 효과
- [x] 나간 돈만 표시
- [x] 나간 돈 총액 표시
- [x] 나간 돈 애니메이션 효과
<br>

## 📸 스크린샷

<br>

## 📚 참고문헌 / 기타
-
